services:


  nginx:
    image: openresty/openresty:alpine
    ports:
      - 3000:80

    
    
    volumes:
      - ./nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
  web:
    build: web

    deploy:
      replicas: 5

  # ai-wroker:
  #   deploy:
  #     replicas: 3

  #   build: ai-worker
    
  
  # rabbitmq:
  #   image: rabbitmq:3-management-alpine
  #   ports:
  #       - 5672:5672
  #       - 15672:15672
  redis:
    image: redis


  
    